### ISSUE TITLE
How to training VideoMAE models

### ISSUE THREAD

**Issue by ByeongjunCho** [ControlNet/MARLIN#10]
Hi, Thanks to share your good paper and implementation code.

I try VideoMAE model to compare performance between MARLIN and VideoMAE.

I find MARLIN and VideoMAE emotion recognition performance in Table3(Facial Expression and Sentiment Recognition) and Table7 in your paper.

How to training your own VideoMAE that writed in MARLIN paper? I want to know how to training VideoMAE(preprocessing, model, etc)

Sorry for my English skill.

Thank you

**Comment by ControlNet** [comment]
Hi, the main difference between MARLIN and VideoMAE is the adversarial loss and the masking strategy. Set `mask_strategy` to `"tube"` and `adv_weight` to `0` should be enough to train the VideoMAE.
