### ISSUE TITLE
load the

### ISSUE THREAD

**Issue by Octopus-Detective** [ControlNet/MARLIN#13]

**Comment by Octopus-Detective** [comment]
I followed your instructions to load the model parameters with the following code:
```python
from marlin_pytorch import Marlin

marlin_model = Marlin.from_file("marlin_vit_base_ytf", "./models/Marlin/marlin_vit_base_ytf.full.pt")
```
The path `"./models/Marlin/marlin_vit_base_ytf.full.pt"` is where I put the downloaded parameters from "https://github.com/ControlNet/MARLIN/blob/master/MODEL_ZOO.md". However, after loading, I keep getting messages like:
```
module.marlin_model.encoder.patch_embedding.projection.weight False
module.marlin_model.encoder.patch_embedding.projection.bias False
module.marlin_model.encoder.pos_embedding.emb False
...
```
It seems like the parameters were not loaded correctly. Could you please help me understand what might be going wrong?

**Comment by ControlNet** [comment]
It also works fine from my end. Could you please provide the versions of `python`, `pytorch`, `marlin_pytorch`.
![image](https://github.com/ControlNet/MARLIN/assets/12800094/61eba592-13f8-4775-a46f-898eed02c557)

Maybe it is because the checkpoint is broken when downloading. Can you try re-download the checkpoint?

**Comment by Octopus-Detective** [comment]
Thank you for your prompt response. The versions of my environment are Python 3.8, PyTorch 2.1, and marlin-pytorch 0.3.4.

**Comment by Octopus-Detective** [comment]
i have tried to re-download the checkpoint for several times, but it did not work.

**Comment by ControlNet** [comment]
I tried the exactly same versions and it will work. I'm not sure about the problem. Could you please share the error message?

**Comment by Octopus-Detective** [comment]
Thank you so much for your help. I'm not experiencing any errors, but it just shows that the parameters can't be loaded! Could you perhaps send a copy of the parameters you're using to my email? My email address is yhzhang@mail.ustc.edu.cn.

**Comment by ControlNet** [comment]
I think there is no other version of checkpoints for you. Please try the current one in different environments.
