### ISSUE TITLE
prediction model for custom video

### ISSUE THREAD

**Issue by pradeepkc11** [ControlNet/MARLIN#15]
can you please upload the script for prediction model for single video so that i can check how it will perform

**Comment by ControlNet** [comment]
I think inference (feature extraction) can be done by simply apply `features = model.extract_video("path/to/video.mp4")` as shown in readme. If you want an example to extract features for a dataset. Please refer to the CelebV-HQ feature extraction scripts. https://github.com/ControlNet/MARLIN/blob/2547c63b611bcf10c0c46506563a618a72468441/preprocess/celebvhq_extract.py#L1-L43
