### ISSUE TITLE
How to use Marlin for downstream tasks？

### ISSUE THREAD

**Issue by rainbowoldhorse** [ControlNet/MARLIN#19]
Hello author, @ControlNet I want use your Marlin model on Wav2lip. After reviewing the decoder code you provided earlier, I have a few questions that I would like to ask you,

1、I understand that your x is the result of the Marlin encoder. Taking the first merging tensor as an example, it is (B, 8, 768,14,14),
IMG consists of 16 images of the lower half of the face, stacked in the channel,so img shape is (B, 3 * 2, 8, 14, 14). The reason why I understand this is because 768 needs to be added to 6 at the channel, and I cannot think of a better explanation.Is my understanding correct? If not, what should be the original meaning and shape of "x" and "img"?

2、In your decoder code, I cannot infer where the audio features are fused with the Marlin features. How can I integrate the audio?

Sincerely seeking your advice on the above two questions, I hope you can answer my confusion,thanks.

**Comment by ControlNet** [comment]
> 1. Shapes
Assume the arch is ViT-B. From the frame encoder, the face embedding is (B, 1568, 768). Then it is reshaped to (B*16, 384, 14, 14) following the original wav2lip. Same, the audio embedding is (B*16, 384, 1, 1) then reshaped to (B*16, 384, 14, 14). 

> 2、In your decoder code, I cannot infer where the audio features are fused with the Marlin features. How can I integrate the audio?
With the vanilla wav2lip audio encoder, the audio is mapped to the audio feature. Then the audio feature and frame features are concatenated as the input of decoder with the shape (B*16, 384+384, 14, 14)

**Comment by rainbowoldhorse** [comment]
Thank you very much for your answer!  I have three more questions to confirm with you.

1. Is Marlin's input used as a reference frame for 16 full face images or 16 masked half of the images to be restored (B, 3, 16, 224, 224)? 

2. Is "img"(In your decoder for wav2lip) 16 half face images and 16 full face images stacked at the channel (B*16, 3+3, 224, 224)?

3. When using the LRS2 dataset, do you directly resize the images to (224, 224)?

**Comment by ControlNet** [comment]
For 1, and 2, what we mainly did for this is just replacing the architecture of encoder and decoder to fit ViT archiecture. Also the temporal size are modified to 16. We didn't change others in wav2lip, therefore we called this method "wav2lip + MARLIN" to show it is just a slight modification rather than a new novelty method.

For 3, yes. After the output is generated, we resized it back to fit the input shape of syncnet.

**Comment by rainbowoldhorse** [comment]
Sincerely thank you for your reply.

**Comment by ggaabe** [comment]
this is awesome stuff. @rainbowoldhorse would love to see what you're building with this, I'm about to try to do what you're doing here. what hardware are you using for training? I'm probably going to try running training on an M2 mac but not sure yet if it'll be enough

**Comment by rainbowoldhorse** [comment]
> this is awesome stuff. @rainbowoldhorse would love to see what you're building with this, I'm about to try to do what you're doing here. what hardware are you using for training? I'm probably going to try running training on an M2 mac but not sure yet if it'll be enough

I'm sorry, I'm not sure if Mac can run machine learning models. I haven't used Mac before, but I can run it using a 1060 (6G) graphics card in Windows/Linux,
