### ISSUE TITLE
How to finetune the pre-trained MARLIN encoder for a video classification task?

### ISSUE THREAD

**Issue by imxtx** [ControlNet/MARLIN#21]
Thank you for this great work! I have a video classification task, how to finetune the pre-trained MARLIN encoder? I have videos with an average length of 5 mins. What should I do to prepare the dataset? What parts of code should I modify?

**Comment by ControlNet** [comment]
Hi, please check the finetune code for CelebV-HQ. I think it is easy to adapat your dataset to it.

**Comment by imxtx** [comment]
Thank you very much. I'll look into it.

**Comment by imxtx** [comment]
Hi authors, I tried to preprocess my custom videos like the celebv-hq dataset, but I found that the output video jitters between frames because the face cropping bounding boxes are different between frames. I'm wondering if is it okay to use them to finetune?

**Comment by ControlNet** [comment]
Hi, you can have a try with the naive frame-level cropping. If it doesn't work well, you can try to fix the crop size to make it have less "jitters".

**Comment by imxtx** [comment]
I want to download the pretrained model. May I ask what does Encoder MACs mean? Thank you!
<img width="145" alt="image" src="https://github.com/ControlNet/MARLIN/assets/93981430/42872660-9959-4abf-b16e-4248a75c342f">

**Comment by ControlNet** [comment]
MACs is Multiply-Accumulate Operations, to measure the time complexity of the model.

**Comment by imxtx** [comment]
> MACs is Multiply-Accumulate Operations, to measure the time complexity of the model.

Thank you very much.
